/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from '../src/routes/__root'
import { Route as PhilosophyRouteImport } from '../src/routes/philosophy'
import { Route as CheckoutRouteImport } from '../src/routes/checkout'
import { Route as IndexRouteImport } from '../src/routes/index'
import { Route as ProductSlugRouteImport } from '../src/routes/product.$slug'
import { Route as PoliciesHandleRouteImport } from '../src/routes/policies.$handle'
import { Route as CollectionsSeriesRouteImport } from '../src/routes/collections.$series'

const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesHandleRoute = PoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSeriesRoute = CollectionsSeriesRouteImport.update({
  id: '/collections/$series',
  path: '/collections/$series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  PhilosophyRoute: typeof PhilosophyRoute
  CollectionsSeriesRoute: typeof CollectionsSeriesRoute
  PoliciesHandleRoute: typeof PoliciesHandleRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  PhilosophyRoute: PhilosophyRoute,
  CollectionsSeriesRoute: CollectionsSeriesRoute,
  PoliciesHandleRoute: PoliciesHandleRoute,
  ProductSlugRoute: ProductSlugRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()