/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRoute } from './routes/__root'

export interface FileRoutesByPath {}

export interface FileRoutesByTo {}

export interface FileRoutesById {
  __root__: typeof rootRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByPath
  fullPaths: never
  fileRoutesByTo: FileRoutesByTo
  to: never
  id: '__root__'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {}

const rootRouteChildren: RootRouteChildren = {}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)

/* prettier-ignore-end */