/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PoliciesHandleRouteImport } from './routes/policies.$handle'
import { Route as CollectionsSeriesRouteImport } from './routes/collections.$series'

const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesHandleRoute = PoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSeriesRoute = CollectionsSeriesRouteImport.update({
  id: '/collections/$series',
  path: '/collections/$series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/philosophy': typeof PhilosophyRoute
  '/collections/$series': typeof CollectionsSeriesRoute
  '/policies/$handle': typeof PoliciesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/catalogue'
    | '/checkout'
    | '/new-arrivals'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/catalogue'
    | '/checkout'
    | '/new-arrivals'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/catalogue'
    | '/checkout'
    | '/new-arrivals'
    | '/philosophy'
    | '/collections/$series'
    | '/policies/$handle'
    | '/product/$slug'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CatalogueRoute: typeof CatalogueRoute
  CheckoutRoute: typeof CheckoutRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PhilosophyRoute: typeof PhilosophyRoute
  CollectionsSeriesRoute: typeof CollectionsSeriesRoute
  PoliciesHandleRoute: typeof PoliciesHandleRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$handle': {
      id: '/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/policies/$handle'
      preLoaderRoute: typeof PoliciesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$series': {
      id: '/collections/$series'
      path: '/collections/$series'
      fullPath: '/collections/$series'
      preLoaderRoute: typeof CollectionsSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CatalogueRoute: CatalogueRoute,
  CheckoutRoute: CheckoutRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PhilosophyRoute: PhilosophyRoute,
  CollectionsSeriesRoute: CollectionsSeriesRoute,
  PoliciesHandleRoute: PoliciesHandleRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
